version: 2

builds:
  - id: imprint
    main: ./cmd/imprint
    binary: imprint
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.Version={{.Version}}

archives:
  - id: imprint
    builds:
      - imprint
    format: tar.gz
    name_template: "imprint_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: kessler-frost
    name: imprint
  prerelease: auto
